### ISSUE TITLE
Why does reefer swallow environment variables by default?

### ISSUE THREAD

**Issue by dougborg** [docker-infra/reefer#1]
Just a quick question on the design choice here. 

Also, would it be possible to pass a pattern to `-e=` instead of listing out a whole bunch of environment variables? Or maybe have an option to pass the entire environment through?

**Comment by discordianfish** [comment]
For security reasons. For instance I use reefer to pass TLS keys to my application - but I don't want them to be accessible to every application running in my container.

But @bdupras just implemented -E to pass through all env vars, so you can use that.
