### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by abraithwaite** [docker-infra/reefer#4]
0.0.4 doesn't have b98f165e0d54abd25754d1b8c23719ae46c1c0bb which looks to be a pretty important fix :-)

**Comment by HazCod** [comment]
Paging @discordianfish

**Comment by discordianfish** [comment]
Not working at Docker anymore, pinging @xbglowx for a new release.

**Comment by xbglowx** [comment]
I will take a look at this today.

**Comment by xbglowx** [comment]
I created v0.0.5
